---

- name: create virtualenv 
  sudo_user: "{{ app_user }}"
  raw: "source virtualenvwrapper.sh && mkvirtualenv {{ application_name }}"
  args:
    chdir: "/home/{{ app_user }}"

- name: Create the application log files
  command: touch "{{ application_log_file_base }}-{{ item }}.log"
           creates="{{ application_log_file_base }}-{{ item }}.log"
  with_items: logs

- name: Create the virtualenv postactivate script to set environment variables
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes

- name: Set permission to the application log file
  file: path="{{ application_log_file_base }}-{{ item }}.log"
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0664
        state=file
  with_items: logs
