- name: install supervisor
  apt: pkg=supervisor state=present update_cache=true

- name: installing tasks
  copy: src={{ item }}.conf dest={{ supervisor_config_dir }}
  with_items: tasks

- name: stop services
  service: name={{ item }} state=stopped
  with_items:
    - nginx

- name: create log dir
  file: path={{ application_log_dir }} state=directory
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}

- name: update supervisor
  command: "{{ supervisorctl_command }} update"

- name: restart tasks
  command: "{{ supervisorctl_command }} restart {{ item }}:*"
  with_items: tasks
  
